global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ['farmbix_backend:8000']
      - labels:
          group: 'production'